// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.44) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(cholera_model)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(N, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(E0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(A0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(M0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Sev0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Mu0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Mt0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Sevu0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Sevt0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Ra0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Rs0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(V10, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(V20, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Du0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(Dt0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(C0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(prop_asym, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(incubation_time, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(duration_asym, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(duration_sym, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(time_to_next_stage, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(p_progress_severe, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(immunity_asym, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(immunity_sym, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_p2p, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(trans_prob, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(drift_volatility, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(drift_reversion, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(time_to_contaminate, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(water_clearance_time, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(contam_half_sat, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(shed_asym, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(shed_mild, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(shed_severe, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(contam_scale, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(seek_mild, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(seek_severe, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(orc_capacity, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(ctc_capacity, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(treated_shed_mult_orc, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(treated_shed_mult_ctc, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(fatality_treated, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(fatality_untreated, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(chlor_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(chlor_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(chlor_effect, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(hyg_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(hyg_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(hyg_effect, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(lat_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(lat_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(lat_effect, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(cati_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(cati_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(cati_effect, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(orc_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(orc_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(ctc_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(ctc_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax1_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax1_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax1_total_doses, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax2_start, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax2_end, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax2_total_doses, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax1_schedule_time, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax1_schedule_doses, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(n_vax1_schedule, type = "int", rank = 0, required = TRUE, constant = TRUE)]]
// [[dust2::parameter(vax2_schedule_time, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax2_schedule_doses, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(n_vax2_schedule, type = "int", rank = 0, required = TRUE, constant = TRUE)]]
// [[dust2::parameter(ve_1, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(ve_2, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax_immunity_1, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vax_immunity_2, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(reporting_rate, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(obs_size, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(death_reporting_rate, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(obs_size_deaths, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class cholera_model {
public:
  cholera_model() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 34> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> vax1_schedule_time;
      dust2::array::dimensions<1> vax1_schedule_doses;
      dust2::array::dimensions<1> vax2_schedule_time;
      dust2::array::dimensions<1> vax2_schedule_doses;
    } dim;
    real_type N;
    real_type E0;
    real_type A0;
    real_type M0;
    real_type Sev0;
    real_type Mu0;
    real_type Mt0;
    real_type Sevu0;
    real_type Sevt0;
    real_type Ra0;
    real_type Rs0;
    real_type V10;
    real_type V20;
    real_type Du0;
    real_type Dt0;
    real_type C0;
    real_type prop_asym;
    real_type incubation_time;
    real_type duration_asym;
    real_type duration_sym;
    real_type time_to_next_stage;
    real_type p_progress_severe;
    real_type immunity_asym;
    real_type immunity_sym;
    real_type beta_p2p;
    real_type trans_prob;
    real_type drift_volatility;
    real_type drift_reversion;
    real_type time_to_contaminate;
    real_type water_clearance_time;
    real_type contam_half_sat;
    real_type shed_asym;
    real_type shed_mild;
    real_type shed_severe;
    real_type contam_scale;
    real_type seek_mild;
    real_type seek_severe;
    real_type orc_capacity;
    real_type ctc_capacity;
    real_type treated_shed_mult_orc;
    real_type treated_shed_mult_ctc;
    real_type fatality_treated;
    real_type fatality_untreated;
    real_type chlor_start;
    real_type chlor_end;
    real_type chlor_effect;
    real_type hyg_start;
    real_type hyg_end;
    real_type hyg_effect;
    real_type lat_start;
    real_type lat_end;
    real_type lat_effect;
    real_type cati_start;
    real_type cati_end;
    real_type cati_effect;
    real_type orc_start;
    real_type orc_end;
    real_type ctc_start;
    real_type ctc_end;
    real_type vax1_start;
    real_type vax1_end;
    real_type vax1_total_doses;
    real_type vax2_start;
    real_type vax2_end;
    real_type vax2_total_doses;
    int n_vax1_schedule;
    int n_vax2_schedule;
    real_type ve_1;
    real_type ve_2;
    real_type vax_immunity_1;
    real_type vax_immunity_2;
    real_type reporting_rate;
    real_type obs_size;
    real_type death_reporting_rate;
    real_type obs_size_deaths;
    std::vector<real_type> vax1_schedule_time;
    std::vector<real_type> vax1_schedule_doses;
    std::vector<real_type> vax2_schedule_time;
    std::vector<real_type> vax2_schedule_doses;
    dust2::interpolate::InterpolateConstant<real_type> interpolate_vax1_doses_daily;
    dust2::interpolate::InterpolateConstant<real_type> interpolate_vax2_doses_daily;
  };
  struct internal_state {};
  struct data_type {
    real_type cases;
    real_type deaths;
    real_type obs_interval;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type N = dust2::r::read_real(parameters, "N", 540000);
    const real_type E0 = dust2::r::read_real(parameters, "E0", 0);
    const real_type A0 = dust2::r::read_real(parameters, "A0", 0);
    const real_type M0 = dust2::r::read_real(parameters, "M0", 0);
    const real_type Sev0 = dust2::r::read_real(parameters, "Sev0", 2);
    const real_type Mu0 = dust2::r::read_real(parameters, "Mu0", 0);
    const real_type Mt0 = dust2::r::read_real(parameters, "Mt0", 0);
    const real_type Sevu0 = dust2::r::read_real(parameters, "Sevu0", 0);
    const real_type Sevt0 = dust2::r::read_real(parameters, "Sevt0", 0);
    const real_type Ra0 = dust2::r::read_real(parameters, "Ra0", 0);
    const real_type Rs0 = dust2::r::read_real(parameters, "Rs0", 0);
    const real_type V10 = dust2::r::read_real(parameters, "V10", 0);
    const real_type V20 = dust2::r::read_real(parameters, "V20", 0);
    const real_type Du0 = dust2::r::read_real(parameters, "Du0", 0);
    const real_type Dt0 = dust2::r::read_real(parameters, "Dt0", 0);
    const real_type C0 = dust2::r::read_real(parameters, "C0", 0);
    const real_type prop_asym = dust2::r::read_real(parameters, "prop_asym", static_cast<real_type>(0.75));
    const real_type incubation_time = dust2::r::read_real(parameters, "incubation_time", static_cast<real_type>(4.8449999999999998));
    const real_type duration_asym = dust2::r::read_real(parameters, "duration_asym", 5);
    const real_type duration_sym = dust2::r::read_real(parameters, "duration_sym", static_cast<real_type>(14.48));
    const real_type time_to_next_stage = dust2::r::read_real(parameters, "time_to_next_stage", 1);
    const real_type p_progress_severe = dust2::r::read_real(parameters, "p_progress_severe", static_cast<real_type>(0.29999999999999999));
    const real_type immunity_asym = dust2::r::read_real(parameters, "immunity_asym", 180);
    const real_type immunity_sym = dust2::r::read_real(parameters, "immunity_sym", 1095);
    const real_type beta_p2p = dust2::r::read_real(parameters, "beta_p2p", static_cast<real_type>(0.050000000000000003));
    const real_type trans_prob = dust2::r::read_real(parameters, "trans_prob", static_cast<real_type>(0.055));
    const real_type drift_volatility = dust2::r::read_real(parameters, "drift_volatility", static_cast<real_type>(0.050000000000000003));
    const real_type drift_reversion = dust2::r::read_real(parameters, "drift_reversion", static_cast<real_type>(0.050000000000000003));
    const real_type time_to_contaminate = dust2::r::read_real(parameters, "time_to_contaminate", static_cast<real_type>(19.074999999999999));
    const real_type water_clearance_time = dust2::r::read_real(parameters, "water_clearance_time", 30);
    const real_type contam_half_sat = dust2::r::read_real(parameters, "contam_half_sat", 1);
    const real_type shed_asym = dust2::r::read_real(parameters, "shed_asym", 90690);
    const real_type shed_mild = dust2::r::read_real(parameters, "shed_mild", 9500500);
    const real_type shed_severe = dust2::r::read_real(parameters, "shed_severe", 32945000);
    const real_type contam_scale = dust2::r::read_real(parameters, "contam_scale", 1e+10);
    const real_type seek_mild = dust2::r::read_real(parameters, "seek_mild", static_cast<real_type>(0.29999999999999999));
    const real_type seek_severe = dust2::r::read_real(parameters, "seek_severe", static_cast<real_type>(0.68000000000000005));
    const real_type orc_capacity = dust2::r::read_real(parameters, "orc_capacity", 500);
    const real_type ctc_capacity = dust2::r::read_real(parameters, "ctc_capacity", 100);
    const real_type treated_shed_mult_orc = dust2::r::read_real(parameters, "treated_shed_mult_orc", static_cast<real_type>(0.5));
    const real_type treated_shed_mult_ctc = dust2::r::read_real(parameters, "treated_shed_mult_ctc", 0);
    const real_type fatality_treated = dust2::r::read_real(parameters, "fatality_treated", static_cast<real_type>(0.0020999999999999999));
    const real_type fatality_untreated = dust2::r::read_real(parameters, "fatality_untreated", static_cast<real_type>(0.5));
    const real_type chlor_start = dust2::r::read_real(parameters, "chlor_start", 0);
    const real_type chlor_end = dust2::r::read_real(parameters, "chlor_end", 0);
    const real_type chlor_effect = dust2::r::read_real(parameters, "chlor_effect", 0);
    const real_type hyg_start = dust2::r::read_real(parameters, "hyg_start", 0);
    const real_type hyg_end = dust2::r::read_real(parameters, "hyg_end", 0);
    const real_type hyg_effect = dust2::r::read_real(parameters, "hyg_effect", 0);
    const real_type lat_start = dust2::r::read_real(parameters, "lat_start", 0);
    const real_type lat_end = dust2::r::read_real(parameters, "lat_end", 0);
    const real_type lat_effect = dust2::r::read_real(parameters, "lat_effect", 0);
    const real_type cati_start = dust2::r::read_real(parameters, "cati_start", 0);
    const real_type cati_end = dust2::r::read_real(parameters, "cati_end", 0);
    const real_type cati_effect = dust2::r::read_real(parameters, "cati_effect", 0);
    const real_type orc_start = dust2::r::read_real(parameters, "orc_start", 0);
    const real_type orc_end = dust2::r::read_real(parameters, "orc_end", 0);
    const real_type ctc_start = dust2::r::read_real(parameters, "ctc_start", 0);
    const real_type ctc_end = dust2::r::read_real(parameters, "ctc_end", 0);
    const real_type vax1_start = dust2::r::read_real(parameters, "vax1_start", 0);
    const real_type vax1_end = dust2::r::read_real(parameters, "vax1_end", 0);
    const real_type vax1_total_doses = dust2::r::read_real(parameters, "vax1_total_doses", 0);
    const real_type vax2_start = dust2::r::read_real(parameters, "vax2_start", 0);
    const real_type vax2_end = dust2::r::read_real(parameters, "vax2_end", 0);
    const real_type vax2_total_doses = dust2::r::read_real(parameters, "vax2_total_doses", 0);
    const int n_vax1_schedule = dust2::r::read_int(parameters, "n_vax1_schedule");
    const int n_vax2_schedule = dust2::r::read_int(parameters, "n_vax2_schedule");
    const real_type ve_1 = dust2::r::read_real(parameters, "ve_1", static_cast<real_type>(0.40000000000000002));
    const real_type ve_2 = dust2::r::read_real(parameters, "ve_2", static_cast<real_type>(0.69999999999999996));
    const real_type vax_immunity_1 = dust2::r::read_real(parameters, "vax_immunity_1", 180);
    const real_type vax_immunity_2 = dust2::r::read_real(parameters, "vax_immunity_2", 1095);
    const real_type reporting_rate = dust2::r::read_real(parameters, "reporting_rate", static_cast<real_type>(0.20000000000000001));
    const real_type obs_size = dust2::r::read_real(parameters, "obs_size", 25);
    const real_type death_reporting_rate = dust2::r::read_real(parameters, "death_reporting_rate", static_cast<real_type>(0.5));
    const real_type obs_size_deaths = dust2::r::read_real(parameters, "obs_size_deaths", 5);
    dim.vax1_schedule_time.set({static_cast<size_t>(n_vax1_schedule)});
    dim.vax1_schedule_doses.set({static_cast<size_t>(n_vax1_schedule)});
    dim.vax2_schedule_time.set({static_cast<size_t>(n_vax2_schedule)});
    dim.vax2_schedule_doses.set({static_cast<size_t>(n_vax2_schedule)});
    std::vector<real_type> vax1_schedule_time(dim.vax1_schedule_time.size);
    dust2::r::read_real_array(parameters, dim.vax1_schedule_time, vax1_schedule_time.data(), "vax1_schedule_time", true);
    std::vector<real_type> vax1_schedule_doses(dim.vax1_schedule_doses.size);
    dust2::r::read_real_array(parameters, dim.vax1_schedule_doses, vax1_schedule_doses.data(), "vax1_schedule_doses", true);
    std::vector<real_type> vax2_schedule_time(dim.vax2_schedule_time.size);
    dust2::r::read_real_array(parameters, dim.vax2_schedule_time, vax2_schedule_time.data(), "vax2_schedule_time", true);
    std::vector<real_type> vax2_schedule_doses(dim.vax2_schedule_doses.size);
    dust2::r::read_real_array(parameters, dim.vax2_schedule_doses, vax2_schedule_doses.data(), "vax2_schedule_doses", true);
    const auto interpolate_vax1_doses_daily = dust2::interpolate::InterpolateConstant(vax1_schedule_time, vax1_schedule_doses, "vax1_schedule_time", "vax1_schedule_doses");
    const auto interpolate_vax2_doses_daily = dust2::interpolate::InterpolateConstant(vax2_schedule_time, vax2_schedule_doses, "vax2_schedule_time", "vax2_schedule_doses");
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"E", {}},
      {"A", {}},
      {"M", {}},
      {"Sev", {}},
      {"Mu", {}},
      {"Mt", {}},
      {"Sevu", {}},
      {"Sevt", {}},
      {"Ra", {}},
      {"Rs", {}},
      {"V1", {}},
      {"V2", {}},
      {"Du", {}},
      {"Dt", {}},
      {"C", {}},
      {"log_trans_drift", {}},
      {"inc_infections", {}},
      {"inc_symptoms", {}},
      {"inc_deaths", {}},
      {"inc_vax1", {}},
      {"inc_vax2", {}},
      {"inc_infections_weekly", {}},
      {"inc_symptoms_weekly", {}},
      {"inc_deaths_weekly", {}},
      {"inc_vax1_weekly", {}},
      {"inc_vax2_weekly", {}},
      {"cum_infections", {}},
      {"cum_symptoms", {}},
      {"cum_deaths", {}},
      {"cum_vax1", {}},
      {"cum_vax2", {}},
      {"cum_orc_treated", {}},
      {"cum_ctc_treated", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, N, E0, A0, M0, Sev0, Mu0, Mt0, Sevu0, Sevt0, Ra0, Rs0, V10, V20, Du0, Dt0, C0, prop_asym, incubation_time, duration_asym, duration_sym, time_to_next_stage, p_progress_severe, immunity_asym, immunity_sym, beta_p2p, trans_prob, drift_volatility, drift_reversion, time_to_contaminate, water_clearance_time, contam_half_sat, shed_asym, shed_mild, shed_severe, contam_scale, seek_mild, seek_severe, orc_capacity, ctc_capacity, treated_shed_mult_orc, treated_shed_mult_ctc, fatality_treated, fatality_untreated, chlor_start, chlor_end, chlor_effect, hyg_start, hyg_end, hyg_effect, lat_start, lat_end, lat_effect, cati_start, cati_end, cati_effect, orc_start, orc_end, ctc_start, ctc_end, vax1_start, vax1_end, vax1_total_doses, vax2_start, vax2_end, vax2_total_doses, n_vax1_schedule, n_vax2_schedule, ve_1, ve_2, vax_immunity_1, vax_immunity_2, reporting_rate, obs_size, death_reporting_rate, obs_size_deaths, vax1_schedule_time, vax1_schedule_doses, vax2_schedule_time, vax2_schedule_doses, interpolate_vax1_doses_daily, interpolate_vax2_doses_daily};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto cases = dust2::r::read_real(data, "cases", NA_REAL);
    auto deaths = dust2::r::read_real(data, "deaths", NA_REAL);
    auto obs_interval = dust2::r::read_real(data, "obs_interval", NA_REAL);
    return data_type{cases, deaths, obs_interval};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.N = dust2::r::read_real(parameters, "N", shared.N);
    shared.E0 = dust2::r::read_real(parameters, "E0", shared.E0);
    shared.A0 = dust2::r::read_real(parameters, "A0", shared.A0);
    shared.M0 = dust2::r::read_real(parameters, "M0", shared.M0);
    shared.Sev0 = dust2::r::read_real(parameters, "Sev0", shared.Sev0);
    shared.Mu0 = dust2::r::read_real(parameters, "Mu0", shared.Mu0);
    shared.Mt0 = dust2::r::read_real(parameters, "Mt0", shared.Mt0);
    shared.Sevu0 = dust2::r::read_real(parameters, "Sevu0", shared.Sevu0);
    shared.Sevt0 = dust2::r::read_real(parameters, "Sevt0", shared.Sevt0);
    shared.Ra0 = dust2::r::read_real(parameters, "Ra0", shared.Ra0);
    shared.Rs0 = dust2::r::read_real(parameters, "Rs0", shared.Rs0);
    shared.V10 = dust2::r::read_real(parameters, "V10", shared.V10);
    shared.V20 = dust2::r::read_real(parameters, "V20", shared.V20);
    shared.Du0 = dust2::r::read_real(parameters, "Du0", shared.Du0);
    shared.Dt0 = dust2::r::read_real(parameters, "Dt0", shared.Dt0);
    shared.C0 = dust2::r::read_real(parameters, "C0", shared.C0);
    shared.prop_asym = dust2::r::read_real(parameters, "prop_asym", shared.prop_asym);
    shared.incubation_time = dust2::r::read_real(parameters, "incubation_time", shared.incubation_time);
    shared.duration_asym = dust2::r::read_real(parameters, "duration_asym", shared.duration_asym);
    shared.duration_sym = dust2::r::read_real(parameters, "duration_sym", shared.duration_sym);
    shared.time_to_next_stage = dust2::r::read_real(parameters, "time_to_next_stage", shared.time_to_next_stage);
    shared.p_progress_severe = dust2::r::read_real(parameters, "p_progress_severe", shared.p_progress_severe);
    shared.immunity_asym = dust2::r::read_real(parameters, "immunity_asym", shared.immunity_asym);
    shared.immunity_sym = dust2::r::read_real(parameters, "immunity_sym", shared.immunity_sym);
    shared.beta_p2p = dust2::r::read_real(parameters, "beta_p2p", shared.beta_p2p);
    shared.trans_prob = dust2::r::read_real(parameters, "trans_prob", shared.trans_prob);
    shared.drift_volatility = dust2::r::read_real(parameters, "drift_volatility", shared.drift_volatility);
    shared.drift_reversion = dust2::r::read_real(parameters, "drift_reversion", shared.drift_reversion);
    shared.time_to_contaminate = dust2::r::read_real(parameters, "time_to_contaminate", shared.time_to_contaminate);
    shared.water_clearance_time = dust2::r::read_real(parameters, "water_clearance_time", shared.water_clearance_time);
    shared.contam_half_sat = dust2::r::read_real(parameters, "contam_half_sat", shared.contam_half_sat);
    shared.shed_asym = dust2::r::read_real(parameters, "shed_asym", shared.shed_asym);
    shared.shed_mild = dust2::r::read_real(parameters, "shed_mild", shared.shed_mild);
    shared.shed_severe = dust2::r::read_real(parameters, "shed_severe", shared.shed_severe);
    shared.contam_scale = dust2::r::read_real(parameters, "contam_scale", shared.contam_scale);
    shared.seek_mild = dust2::r::read_real(parameters, "seek_mild", shared.seek_mild);
    shared.seek_severe = dust2::r::read_real(parameters, "seek_severe", shared.seek_severe);
    shared.orc_capacity = dust2::r::read_real(parameters, "orc_capacity", shared.orc_capacity);
    shared.ctc_capacity = dust2::r::read_real(parameters, "ctc_capacity", shared.ctc_capacity);
    shared.treated_shed_mult_orc = dust2::r::read_real(parameters, "treated_shed_mult_orc", shared.treated_shed_mult_orc);
    shared.treated_shed_mult_ctc = dust2::r::read_real(parameters, "treated_shed_mult_ctc", shared.treated_shed_mult_ctc);
    shared.fatality_treated = dust2::r::read_real(parameters, "fatality_treated", shared.fatality_treated);
    shared.fatality_untreated = dust2::r::read_real(parameters, "fatality_untreated", shared.fatality_untreated);
    shared.chlor_start = dust2::r::read_real(parameters, "chlor_start", shared.chlor_start);
    shared.chlor_end = dust2::r::read_real(parameters, "chlor_end", shared.chlor_end);
    shared.chlor_effect = dust2::r::read_real(parameters, "chlor_effect", shared.chlor_effect);
    shared.hyg_start = dust2::r::read_real(parameters, "hyg_start", shared.hyg_start);
    shared.hyg_end = dust2::r::read_real(parameters, "hyg_end", shared.hyg_end);
    shared.hyg_effect = dust2::r::read_real(parameters, "hyg_effect", shared.hyg_effect);
    shared.lat_start = dust2::r::read_real(parameters, "lat_start", shared.lat_start);
    shared.lat_end = dust2::r::read_real(parameters, "lat_end", shared.lat_end);
    shared.lat_effect = dust2::r::read_real(parameters, "lat_effect", shared.lat_effect);
    shared.cati_start = dust2::r::read_real(parameters, "cati_start", shared.cati_start);
    shared.cati_end = dust2::r::read_real(parameters, "cati_end", shared.cati_end);
    shared.cati_effect = dust2::r::read_real(parameters, "cati_effect", shared.cati_effect);
    shared.orc_start = dust2::r::read_real(parameters, "orc_start", shared.orc_start);
    shared.orc_end = dust2::r::read_real(parameters, "orc_end", shared.orc_end);
    shared.ctc_start = dust2::r::read_real(parameters, "ctc_start", shared.ctc_start);
    shared.ctc_end = dust2::r::read_real(parameters, "ctc_end", shared.ctc_end);
    shared.vax1_start = dust2::r::read_real(parameters, "vax1_start", shared.vax1_start);
    shared.vax1_end = dust2::r::read_real(parameters, "vax1_end", shared.vax1_end);
    shared.vax1_total_doses = dust2::r::read_real(parameters, "vax1_total_doses", shared.vax1_total_doses);
    shared.vax2_start = dust2::r::read_real(parameters, "vax2_start", shared.vax2_start);
    shared.vax2_end = dust2::r::read_real(parameters, "vax2_end", shared.vax2_end);
    shared.vax2_total_doses = dust2::r::read_real(parameters, "vax2_total_doses", shared.vax2_total_doses);
    shared.ve_1 = dust2::r::read_real(parameters, "ve_1", shared.ve_1);
    shared.ve_2 = dust2::r::read_real(parameters, "ve_2", shared.ve_2);
    shared.vax_immunity_1 = dust2::r::read_real(parameters, "vax_immunity_1", shared.vax_immunity_1);
    shared.vax_immunity_2 = dust2::r::read_real(parameters, "vax_immunity_2", shared.vax_immunity_2);
    shared.reporting_rate = dust2::r::read_real(parameters, "reporting_rate", shared.reporting_rate);
    shared.obs_size = dust2::r::read_real(parameters, "obs_size", shared.obs_size);
    shared.death_reporting_rate = dust2::r::read_real(parameters, "death_reporting_rate", shared.death_reporting_rate);
    shared.obs_size_deaths = dust2::r::read_real(parameters, "obs_size_deaths", shared.obs_size_deaths);
    dust2::r::read_real_array(parameters, shared.dim.vax1_schedule_time, shared.vax1_schedule_time.data(), "vax1_schedule_time", false);
    dust2::r::read_real_array(parameters, shared.dim.vax1_schedule_doses, shared.vax1_schedule_doses.data(), "vax1_schedule_doses", false);
    dust2::r::read_real_array(parameters, shared.dim.vax2_schedule_time, shared.vax2_schedule_time.data(), "vax2_schedule_time", false);
    dust2::r::read_real_array(parameters, shared.dim.vax2_schedule_doses, shared.vax2_schedule_doses.data(), "vax2_schedule_doses", false);
    shared.interpolate_vax1_doses_daily = dust2::interpolate::InterpolateConstant(shared.vax1_schedule_time, shared.vax1_schedule_doses, "vax1_schedule_time", "vax1_schedule_doses");
    shared.interpolate_vax2_doses_daily = dust2::interpolate::InterpolateConstant(shared.vax2_schedule_time, shared.vax2_schedule_doses, "vax2_schedule_time", "vax2_schedule_doses");
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = shared.N - shared.E0 - shared.A0 - shared.M0 - shared.Sev0 - shared.Mu0 - shared.Mt0 - shared.Sevu0 - shared.Sevt0 - shared.Ra0 - shared.Rs0 - shared.V10 - shared.V20;
    state[1] = shared.E0;
    state[2] = shared.A0;
    state[3] = shared.M0;
    state[4] = shared.Sev0;
    state[5] = shared.Mu0;
    state[6] = shared.Mt0;
    state[7] = shared.Sevu0;
    state[8] = shared.Sevt0;
    state[9] = shared.Ra0;
    state[10] = shared.Rs0;
    state[11] = shared.V10;
    state[12] = shared.V20;
    state[13] = shared.Du0;
    state[14] = shared.Dt0;
    state[15] = shared.C0;
    state[16] = 0;
    state[17] = 0;
    state[18] = 0;
    state[19] = 0;
    state[20] = 0;
    state[21] = 0;
    state[22] = 0;
    state[23] = 0;
    state[24] = 0;
    state[25] = 0;
    state[26] = 0;
    state[27] = 0;
    state[28] = 0;
    state[29] = shared.Du0 + shared.Dt0;
    state[30] = 0;
    state[31] = 0;
    state[32] = 0;
    state[33] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto E = state[1];
    const auto A = state[2];
    const auto M = state[3];
    const auto Sev = state[4];
    const auto Mu = state[5];
    const auto Mt = state[6];
    const auto Sevu = state[7];
    const auto Sevt = state[8];
    const auto Ra = state[9];
    const auto Rs = state[10];
    const auto V1 = state[11];
    const auto V2 = state[12];
    const auto Du = state[13];
    const auto Dt = state[14];
    const auto C = state[15];
    const auto log_trans_drift = state[16];
    const auto inc_infections = state[17];
    const auto inc_symptoms = state[18];
    const auto inc_deaths = state[19];
    const auto inc_vax1 = state[20];
    const auto inc_vax2 = state[21];
    const auto inc_infections_weekly = state[22];
    const auto inc_symptoms_weekly = state[23];
    const auto inc_deaths_weekly = state[24];
    const auto inc_vax1_weekly = state[25];
    const auto inc_vax2_weekly = state[26];
    const auto cum_infections = state[27];
    const auto cum_symptoms = state[28];
    const auto cum_deaths = state[29];
    const auto cum_vax1 = state[30];
    const auto cum_vax2 = state[31];
    const auto cum_orc_treated = state[32];
    const auto cum_ctc_treated = state[33];
    const real_type trans_drift = monty::math::exp<real_type>(log_trans_drift);
    const real_type I_eff = A + M + Sev + Mu + Mt + Sevu + Sevt;
    const real_type chlor_active = (time >= shared.chlor_start && time < shared.chlor_end ? 1 : 0);
    const real_type hyg_active = (time >= shared.hyg_start && time < shared.hyg_end ? 1 : 0);
    const real_type lat_active = (time >= shared.lat_start && time < shared.lat_end ? 1 : 0);
    const real_type cati_active = (time >= shared.cati_start && time < shared.cati_end ? 1 : 0);
    const real_type orc_active = (time >= shared.orc_start && time < shared.orc_end ? 1 : 0);
    const real_type ctc_active = (time >= shared.ctc_start && time < shared.ctc_end ? 1 : 0);
    const real_type vax1_active = (time >= shared.vax1_start && time < shared.vax1_end ? 1 : 0);
    const real_type vax2_active = (time >= shared.vax2_start && time < shared.vax2_end ? 1 : 0);
    const real_type p_EI = 1 - monty::math::exp<real_type>(-dt / shared.incubation_time);
    const real_type p_rec_asym = 1 - monty::math::exp<real_type>(-dt / shared.duration_asym);
    const real_type p_stage = 1 - monty::math::exp<real_type>(-dt / shared.time_to_next_stage);
    const real_type p_leave_sym = 1 - monty::math::exp<real_type>(-dt / shared.duration_sym);
    const real_type p_wane_Ra = 1 - monty::math::exp<real_type>(-dt / shared.immunity_asym);
    const real_type p_wane_Rs = 1 - monty::math::exp<real_type>(-dt / shared.immunity_sym);
    const real_type p_wane_V1 = 1 - monty::math::exp<real_type>(-dt / shared.vax_immunity_1);
    const real_type p_wane_V2 = 1 - monty::math::exp<real_type>(-dt / shared.vax_immunity_2);
    const real_type env_force = shared.trans_prob * (C / (C + shared.contam_half_sat));
    const real_type p2p_force = shared.beta_p2p * (I_eff / shared.N);
    const real_type vax1_remain = monty::math::max<real_type>(0, shared.vax1_total_doses - cum_vax1);
    const real_type vax2_remain = monty::math::max<real_type>(0, shared.vax2_total_doses - cum_vax2);
    const real_type trans_mult = monty::math::max<real_type>(0, 1 - (chlor_active * shared.chlor_effect + hyg_active * shared.hyg_effect + cati_active * shared.cati_effect));
    const real_type shed_mult = monty::math::max<real_type>(0, 1 - (lat_active * shared.lat_effect));
    const real_type new_I = monty::random::binomial<real_type>(rng_state, E, p_EI);
    const real_type rec_A = monty::random::binomial<real_type>(rng_state, A, p_rec_asym);
    const real_type prog_M = monty::random::binomial<real_type>(rng_state, M, p_stage);
    const real_type prog_Sev = monty::random::binomial<real_type>(rng_state, Sev, p_stage);
    const real_type orc_cap_step = monty::math::floor<real_type>(orc_active * shared.orc_capacity * dt);
    const real_type ctc_cap_step = monty::math::floor<real_type>(ctc_active * shared.ctc_capacity * dt);
    const real_type leave_Mu = monty::random::binomial<real_type>(rng_state, Mu, p_leave_sym);
    const real_type leave_Mt = monty::random::binomial<real_type>(rng_state, Mt, p_leave_sym);
    const real_type leave_Sevu = monty::random::binomial<real_type>(rng_state, Sevu, p_leave_sym);
    const real_type leave_Sevt = monty::random::binomial<real_type>(rng_state, Sevt, p_leave_sym);
    const real_type wane_Ra = monty::random::binomial<real_type>(rng_state, Ra, p_wane_Ra);
    const real_type wane_Rs = monty::random::binomial<real_type>(rng_state, Rs, p_wane_Rs);
    const real_type wane_V1 = monty::random::binomial<real_type>(rng_state, V1, p_wane_V1);
    const real_type wane_V2 = monty::random::binomial<real_type>(rng_state, V2, p_wane_V2);
    const real_type lambda = trans_drift * trans_mult * (p2p_force + env_force);
    const real_type new_A = monty::random::binomial<real_type>(rng_state, new_I, shared.prop_asym);
    const real_type seek_M = monty::random::binomial<real_type>(rng_state, prog_M, shared.seek_mild);
    const real_type seek_Sev = monty::random::binomial<real_type>(rng_state, prog_Sev, shared.seek_severe);
    const real_type death_Sevu = monty::random::binomial<real_type>(rng_state, leave_Sevu, shared.fatality_untreated);
    const real_type death_Sevt = monty::random::binomial<real_type>(rng_state, leave_Sevt, shared.fatality_treated);
    const real_type shed_cfu = shed_mult * (shared.shed_asym * A + shared.shed_mild * (M + Mu) + shared.shed_mild * shared.treated_shed_mult_orc * Mt + shared.shed_severe * (Sev + Sevu) + shared.shed_severe * shared.treated_shed_mult_ctc * Sevt);
    const real_type p_inf = 1 - monty::math::exp<real_type>(-lambda * dt);
    const real_type new_symp = new_I - new_A;
    const real_type treat_orc = monty::math::min<real_type>(seek_M, orc_cap_step);
    const real_type treat_ctc = monty::math::min<real_type>(seek_Sev, ctc_cap_step);
    const real_type rec_Sevu = leave_Sevu - death_Sevu;
    const real_type rec_Sevt = leave_Sevt - death_Sevt;
    const real_type shed_index = shed_cfu / shared.contam_scale;
    const real_type vax1_doses_daily = shared.interpolate_vax1_doses_daily.eval(time);
    const real_type vax2_doses_daily = shared.interpolate_vax2_doses_daily.eval(time);
    const real_type new_E_S = monty::random::binomial<real_type>(rng_state, S, p_inf);
    const real_type new_E_V1 = monty::random::binomial<real_type>(rng_state, V1, monty::math::min<real_type>(1, p_inf * (1 - shared.ve_1)));
    const real_type new_E_V2 = monty::random::binomial<real_type>(rng_state, V2, monty::math::min<real_type>(1, p_inf * (1 - shared.ve_2)));
    const real_type new_Sev = monty::random::binomial<real_type>(rng_state, new_symp, shared.p_progress_severe);
    const real_type to_Mu = prog_M - treat_orc;
    const real_type to_Sevu = prog_Sev - treat_ctc;
    const real_type vax1_daily_doses = (vax1_active > 0 ? vax1_doses_daily : 0);
    const real_type vax2_daily_doses = (vax2_active > 0 ? vax2_doses_daily : 0);
    const real_type dC = (shed_index / monty::math::max<real_type>(static_cast<real_type>(1.0000000000000001e-09), shared.time_to_contaminate)) - (C / monty::math::max<real_type>(static_cast<real_type>(1.0000000000000001e-09), shared.water_clearance_time));
    const real_type new_E = new_E_S + new_E_V1 + new_E_V2;
    const real_type new_M = new_symp - new_Sev;
    const real_type vax1_cap_step = monty::math::floor<real_type>(vax1_daily_doses * dt);
    const real_type vax2_cap_step = monty::math::floor<real_type>(vax2_daily_doses * dt);
    const real_type vax1_admin = monty::math::min<real_type>(S, monty::math::min<real_type>(vax1_remain, vax1_cap_step));
    const real_type vax2_admin = monty::math::min<real_type>(V1, monty::math::min<real_type>(vax2_remain, vax2_cap_step));
    state_next[16] = log_trans_drift - (shared.drift_reversion * log_trans_drift * dt) + monty::random::normal<real_type>(rng_state, 0, shared.drift_volatility * monty::math::sqrt<real_type>(dt));
    state_next[15] = monty::math::max<real_type>(0, C + dt * dC);
    state_next[0] = monty::math::max<real_type>(0, S - new_E_S - vax1_admin + wane_Ra + wane_Rs + wane_V1 + wane_V2);
    state_next[1] = E + new_E - new_I;
    state_next[2] = A + new_A - rec_A;
    state_next[3] = M + new_M - prog_M;
    state_next[4] = Sev + new_Sev - prog_Sev;
    state_next[5] = Mu + to_Mu - leave_Mu;
    state_next[6] = Mt + treat_orc - leave_Mt;
    state_next[7] = Sevu + to_Sevu - leave_Sevu;
    state_next[8] = Sevt + treat_ctc - leave_Sevt;
    state_next[9] = Ra + rec_A - wane_Ra;
    state_next[10] = Rs + leave_Mu + leave_Mt + rec_Sevu + rec_Sevt - wane_Rs;
    state_next[11] = monty::math::max<real_type>(0, V1 + vax1_admin - vax2_admin - wane_V1 - new_E_V1);
    state_next[12] = monty::math::max<real_type>(0, V2 + vax2_admin - wane_V2 - new_E_V2);
    state_next[13] = Du + death_Sevu;
    state_next[14] = Dt + death_Sevt;
    state_next[17] = inc_infections + new_E;
    state_next[18] = inc_symptoms + new_symp;
    state_next[19] = inc_deaths + death_Sevu + death_Sevt;
    state_next[20] = inc_vax1 + vax1_admin;
    state_next[21] = inc_vax2 + vax2_admin;
    state_next[22] = inc_infections_weekly + new_E;
    state_next[23] = inc_symptoms_weekly + new_symp;
    state_next[24] = inc_deaths_weekly + death_Sevu + death_Sevt;
    state_next[25] = inc_vax1_weekly + vax1_admin;
    state_next[26] = inc_vax2_weekly + vax2_admin;
    state_next[27] = cum_infections + new_E;
    state_next[28] = cum_symptoms + new_symp;
    state_next[29] = cum_deaths + death_Sevu + death_Sevt;
    state_next[30] = cum_vax1 + vax1_admin;
    state_next[31] = cum_vax2 + vax2_admin;
    state_next[32] = cum_orc_treated + treat_orc;
    state_next[33] = cum_ctc_treated + treat_ctc;
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {17}}, {1, {18}}, {1, {19}}, {1, {20}}, {1, {21}}, {7, {22}}, {7, {23}}, {7, {24}}, {7, {25}}, {7, {26}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto inc_symptoms = state[18];
    const auto inc_deaths = state[19];
    const auto inc_symptoms_weekly = state[23];
    const auto inc_deaths_weekly = state[24];
    real_type odin_ll = 0;
    const real_type obs_inc_symptoms = (data.obs_interval <= static_cast<real_type>(1.5) ? inc_symptoms : inc_symptoms_weekly);
    const real_type obs_inc_deaths = (data.obs_interval <= static_cast<real_type>(1.5) ? inc_deaths : inc_deaths_weekly);
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.cases, shared.obs_size, shared.reporting_rate * obs_inc_symptoms, true));
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.deaths, shared.obs_size_deaths, shared.death_reporting_rate * obs_inc_deaths, true));
    return odin_ll;
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>
#include <dust2/r/discrete/filter.hpp>
#include <dust2/r/discrete/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_system_cholera_model_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<cholera_model>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_cholera_model_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<cholera_model>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<cholera_model>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<cholera_model>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<cholera_model>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<cholera_model>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<cholera_model>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<cholera_model>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<cholera_model>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<cholera_model>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<cholera_model>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_cholera_model_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<cholera_model>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_cholera_model_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_unfilter_alloc<cholera_model>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed) {
  return dust2::r::dust2_discrete_filter_alloc<cholera_model>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed);
}
[[cpp11::register]]
SEXP dust2_system_cholera_model_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_compare_data<dust2::dust_discrete<cholera_model>>(ptr, r_data, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_cholera_model_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_unfilter_update_pars<dust2::dust_discrete<cholera_model>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_unfilter_cholera_model_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_run<dust2::dust_discrete<cholera_model>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_cholera_model_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_trajectories<dust2::dust_discrete<cholera_model>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_cholera_model_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_snapshots<dust2::dust_discrete<cholera_model>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_cholera_model_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_state<dust2::dust_discrete<cholera_model>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_filter_update_pars<dust2::dust_discrete<cholera_model>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_run<dust2::dust_discrete<cholera_model>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_trajectories<dust2::dust_discrete<cholera_model>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_snapshots<dust2::dust_discrete<cholera_model>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_state<dust2::dust_discrete<cholera_model>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_filter_rng_state<dust2::dust_discrete<cholera_model>>(ptr);
}

[[cpp11::register]]
SEXP dust2_filter_cholera_model_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_filter_set_rng_state<dust2::dust_discrete<cholera_model>>(ptr, r_rng_state);
}
